version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: